import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
 const router=useRouter()
 
  useEffect(() => {
    setTimeout(() => {
      router.push("/invoice")
    }, 2000);
  }, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Invoice App!</a>
        </h1>
      </main>
     </div>
  )
}
